name: frontend_bisarj
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.0-162.1.beta

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_staggered_animations: ^1.1.1
  auto_size_text: ^3.0.0
  lottie: ^3.1.2
  coupon_uikit: ^0.2.0
  awesome_snackbar_content: ^0.1.3
  fluttertoast: ^8.2.8
  intl: ^0.20.2
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  country_code_picker: ^3.0.0
  flutter_otp_text_field: ^1.1.1
  google_mobile_ads: ^5.1.0
  google_maps_flutter: ^2.6.0
  flutter_rating_bar: ^4.0.1
  animated_bottom_navigation_bar: ^1.3.0
  awesome_bottom_bar: ^1.2.3
  flutter_sticky_header: ^0.8.0
  value_layout_builder: ^0.5.0
  graphql_flutter: ^5.2.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/amenities/
    - assets/images/
    - assets/lottie/
    - assets/images/cars/

  fonts:
    - family: AirbnbCereal_W_Bd
      fonts:
        - asset: assets/fonts/AirbnbCereal_W_Bd.otf

    - family: AirbnbCereal_W_Bk
      fonts:
        - asset: assets/fonts/AirbnbCereal_W_Bk.otf

    - family: AirbnbCereal_W_Blk
      fonts:
        - asset: assets/fonts/AirbnbCereal_W_Blk.otf

    - family: AirbnbCereal_W_Lt
      fonts:
        - asset: assets/fonts/AirbnbCereal_W_Lt.otf

    - family: AirbnbCereal_W_Md
      fonts:
        - asset: assets/fonts/AirbnbCereal_W_Md.otf
